services:
    mcbash:
        #network_mode: "container:vpn"
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: mcbash
        environment:
            - TZ=Europe/Berlin
        volumes:
            - ./config:/root/.mcbash
        tty: true
        stdin_open: true
        command: bash
        restart: unless-stopped
