# CONFIG FILE
# ░█▄▒▄█░▄▀▀░██▄▒▄▀▄░▄▀▀░█▄█
# ░█▒▀▒█░▀▄▄▒█▄█░█▀█▒▄██▒█▒█
# This file should be located here: ~/.config/mcbash/mcbash.conf
# If not found, mcbash will look for it here: /etc/mcbash.conf

# Directory where found MACs are stored
destination = $HOME/.mcbash

# Requests
default_request_delay = 2 # delay between two requests (seconds)
default_timeout = 5 # request are considered timeout after <X> seconds

consecutive_timeout_limit = 5 # rotate proxy (or exit) when <X> consecutive timeouts (0 = no limit)
total_timeout_limit = 0       # rotate proxy (or exit) when <X> timeouts (0 = no limit)

default_timebreak = 0 # make a break every <X> requests
default_timebreak_duration = 10 # break duration (seconds)

default_stopping = 0 # stop mcbash after <X> requests (0 = never stop)

default_mac_prefix = "00:1A:79:" # default MAC prefix

# Default MAC boundaries
default_first_mac = "00:1A:79:00:00:00"
default_last_mac  = "00:1A:79:FF:FF:FF"

# Don't ask for parameters setting at startup
no_interactive = false # or true
