.TH McCheckerBash 1 mcbash
.SH NAME
mcbash \- bash script to scan for valid MAC addresses on Stalker Portal servers.
.SH SYNOPSIS
.B mcbash
[
.I DNS_URL
]
.SH DESCRIPTION
.B mcbash
scans and stores valid MAC addresses on specified server.
.SH COMMANDS
.TP
.B -w
[
.I requests_per_seconds
]
delay between two requests in seconds (avoid flood). Default delay = 2
.TP
.B -b
[
.I number_of_requests
]
number of requests before pausing.
.TP
.B -d
[
.I duration_in_seconds
]
duration time for each pause. Default duration = 10
.TP
.B -s
[
.I number_of_requests
]
stop
.B mcbash
after X requests.
.TP
.B -k
store expired MAC addresses (valid but expired accounts)
.TP
.B -t
[
.I seconds
]
consider requests timeouted after this delay.
.TP
.B -u
[
.I URL/IP
]
indicate the server URL/IP.
.TP
.B --range
check MAC addresses sequentially.
.TP
.B -F
[
.I xx:xx:xx:xx:xx
]
indicate first MAC address to check.
.TP
.B -L
[
.I xx:xx:xx:xx:xx
]
indicate last MAC address to check.
.TP
.B -np
don't ask for parameters. Default parameters used.
.SH AUTHORS
Written by dougy147 originally in 2022.
.SH LICENSE
GPLv3
