.TH mcbash 1 mcbash
.SH NAME
mcbash \- Customizable and user-friendly MAC scanner.
.SH SYNOPSIS
.B mcbash [OPTS]
.SH DESCRIPTION
.B mcbash
scans MAC addresses on specified server. It supports random scan (default), sequential scan, and from-file scan.
For random and sequential scans, ranges can be specified (lowest and highest MAC).
A checkpoint system is used by default for sequential scans.
.SH OPTIONS
.SS Server
.TP
\f[B]-u\f[R], \f[B]--url\f[R] \f[I]URL/IP\f[R]
Set server location.
.SS Scan mode
.TP
\f[B]--seq\f[R]
Check MACs sequentially.
.TP
\f[B]--range\f[R]
Check within an inclusive range between lower-to-upper bound MAC.
If \f[B]--default\f[R] is set, \f[B]mcbash\f[R] will check for them in the configuration file.
Else if \f[B]--from\f[R] or \f[B]--to\f[R] is not specified, \f[B]mcbash\f[R] will interactively prompt the user.
.TP
\f[B]-F\f[R], \f[B]--from\f[R] \f[I]XX:XX:XX:XX:XX\f[R]
Set lower bound MAC.
.TP
\f[B]-L\f[R], \f[B]--to\f[R] \f[I]XX:XX:XX:XX:XX\f[R]
Set upper bound MAC.
.TP
\f[B]--mac-file\f[R] \f[I]FILE\f[R]
Check MACs provided from \f[I]FILE\f[R]. MACs must be line by line in \f[I]FILE\f[R].
.SS Requests
.TP
\f[B]-w\f[R], \f[B]--wait\f[R] \f[I]SECONDS\f[R]
Delay between two requests in seconds.
.TP
\f[B]-t\f[R], \f[B]--timeout\f[R] \f[I]SECONDS\f[R]
Delay before considering request a timeout.
.TP
\f[B]-b\f[R], \f[B]--break\f[R] \f[I]COUNT\f[R]
Make a break every \f[I]COUNT\f[R] requests.
.TP
\f[B]-d\f[R], \f[B]--pause-for\f[R] \f[I]SECONDS\f[R]
Break duration.
.TP
\f[B]-s\f[R], \f[B]--stop\f[R] \f[I]COUNT\f[R]
Stop 
.B mcbash
after \f[I]COUNT\f[R] requests.
.SS Connections
.TP
\f[B]-P\f[R], \f[B]--proxy\f[R] \f[I][PROTOCOL://]HOST[:PORT]\f[R]
Establish connections through proxy. See \f[B]--proxy-user\f[R] for credentials.
.TP
\f[B]-pu\f[R], \f[B]--proxy-user\f[R] \f[I]USERNAME:PASSWORD\f[R]
Use \f[I]USERNAME\f[R] and \f[I]PASSWORD\f[R] credentials with \f[B]--proxy\f[R].
.TP
\f[B]--proxy-file\f[R] \f[I]FILE\f[R]
Use proxies from \f[I]FILE\f[R] (proxies must be line by line in \f[I]FILE\f[R]).
Rotation occurs each time consecutive timeouts \f[I]COUNT\f[R] reaches the default limit.
.SS Filters
.TP
\f[B]-gr\f[R], \f[B]--genre-regex\f[R] \f[I]REGEX\f[R]
Verify at least one channels category (genre) matches \f[B]REGEX\f[R].
Otherwise, consider MAC invalid and do not store.
Match is case-insensitive.
\f[B]REGEX\f[R] is any extended regular expression.
This is useful when looking for a specific language or category.
For example: "U(nited)?.?K[^r]*" will match "United-Kingdom" or "UK" but not "Ukraine"
.TP
\f[B]-pl\f[R], \f[B]--playable\f[R]
Ensure channels can be played using \f[B]ffprobe\f[R] (dependency).
Otherwise, consider MAC invalid and do not store.
In conjunction with \f[B]--genre-regex\f[R], a channel from a matching genre is selected.
Otherwise a random channel is selected.
.SS Others
.TP
\f[B]-np\f[R], \f[B]--default\f[R]
No interactive startup. Immediate use of default parameters from $HOME/.mcbash/mcbash.conf or /etc/mcbash.conf
.TP
\f[B]--prefix\f[R] \f[I]PREFIX\f[R]
Check MACs starting with \f[I]PREFIX\f[R]. \f[I]PREFIX\f[R] can be any slice of a MAC.
For example: "00:1A:", "00:11:22:33", ...
.TP
\f[B]-k\f[R], \f[B]--keep\f[R]
Store MACs even when they are expired.
.TP
\f[B]-EA\f[R], \f[B]--enhanced-auth\f[R]
Experimental. Add serial number and Device_ID1 to GET requests.
.TP
\f[B]--no-checkpoint\f[R]
Ignore any previous checkpoint and do not store any.
.TP
\f[B]--show-only-mac\f[R]
Only outputs found MACs to stdout. Useful to redirect them to another program.
.TP
\f[B]--version\f[R]
Display \f[B]mcbash\f[R] version and exit.
.TP
\f[B]-h\f[R], \f[B]--help\f[R]
Print a quick help menu and exit.
.SH FILES
.TP
.I /etc/\:\%mcbash\:.conf
Global configuration file (optional). Sourced at startup, before any local configuration file.
.TP
.I $HOME/\:\%.config/\:\%mcbash/\:\%mcbash\:.conf
Local configuration file (optional). Sourced at startup, after any global configuration file.
.SH AUTHORS
Written by dougy147 originally in 2022. https://github.com/dougy147/mcbash
.SH LICENSE
GPLv3
