#!/bin/sh

read_args() {
    local args
    declare -a args=("$@")
    for ((i=0;i<${#args[@]};i++)); do
        case "${args[i]}" in
            --debug)
                debug=true
                debug_verbose_curl=-vvvvvv
                ;;
            -EA|--enhanced-auth)
                enhanced_auth=true
                ;;
            --show-only-mac)
                only_outputs_mac=true
                ;;
            -np|--default)
                avoid_parameters=true
                ;;
            -u|--url)
                URL="${args[i+1]}"
                inspect_from_args --url "${URL}"
                ;;
            -w|--wait)
                request_delay=${args[i+1]}
                inspect_from_args --wait ${request_delay}
                ;;
            -t|--timeout)
                timeout=${args[i+1]}
                inspect_from_args --timeout ${timeout}
                ;;
            -b|--break)
                timebreak=${args[i+1]}
                inspect_from_args --break ${timebreak}
                ;;
            -d|--pause-for)
                timebreak_duration=${args[i+1]}
                inspect_from_args --pause-for ${timebreak_duration}
                ;;
            -s|--stop)
                stopping=${args[i+1]}
                inspect_from_args --stop ${stopping}
                ;;
            -k|--keep)
                keep_expired=${args[i+1]}
                ;;
            --range)
                range=true
                ;;
            --seq)
                seq=true
                range=true
                ;;
            -F|--from)
                range=true
                range_from=${args[i+1]}
                inspect_from_args --from ${range_from}
                ;;
            -L|--to)
                range=true
                range_to=${args[i+1]}
                inspect_from_args --to ${range_to}
                ;;
            -P|--proxy)
                proxy_url=${args[i+1]}
                proxy_url_option="-x $proxy_url"
                ;;
            -pu|--proxy-user)
                proxy_user=${args[i+1]}
                proxy_user_option="--proxy-anyauth --proxy-user $proxy_user"
                ;;
            --proxy-file)
                proxy_from_file=true
                proxy_file=${args[i+1]}
                update_proxy
                ;;
            --no-checkpoint)
                no_checkpoint=true
                ;;
            --prefix)
                prefix=${args[i+1]}
                ;;
            --mac-file)
                read_from_file=true
                file_to_read_mac_from="${args[i+1]}"
                inspect_from_args --mac-file "$file_to_read_mac_from"
                ;;
            -h|--help)
                display_help
                exit 0
                ;;
        esac
    done
}

inspect_from_args() {
    case "$1" in
        --url|-u|URL)                   inspect_URL      "$2"   from_args ;;
        --wait|-w|delay)                inspect_float    $1 $2  from_args ;;
        --timeout|-t|timeout)           inspect_float    $1 $2  from_args ;;
        --break|-b|break)               inspect_int      $1 $2  from_args ;;
        --pause-for|-d|break_duration)  inspect_float    $1 $2  from_args ;;
        --stop|-s|stop)                 inspect_int      $1 $2  from_args ;;
        --from|-F|--to|-L)              inspect_mac      $2     from_args ;;
        --mac-file)                     inspect_mac_file  "$2"  from_args ;;
        *)                              display_problem_inspecting_arguments ;;
    esac
}

inspect_float() {
    local _caller="$1"
    local float="$2"
    local mode=$3
    if ! [[ $float =~ ^([0-9]+)?(\.)?[0-9]+$ ]]; then
        display_bad_float "$_caller"
        if [[ $mode == from_args ]]; then
            exit 1
        else
            return 1
        fi
    fi
    if [[ $mode == from_args && "${float// /}" == "" ]]; then
        display_empty_value "$_caller"
        exit 1
    fi
}

inspect_int() {
    local _caller="$1"
    local int="$2"
    local mode=$3
    if ! [[ $int =~ ^[0-9]+$ ]]; then
        display_bad_int "$_caller"
        if [[ $mode == from_args ]]; then
            exit 1
        else
            return 1
        fi
    fi
    if [[ $mode == "from_args" && "${int// /}" == "" ]]; then
        display_empty_value "$_caller"
        exit 1
    fi
}
