#!/bin/sh

load_config_file() {
    CONFIG_FILE="${CONF_DEST}/mcbash.conf"

    if [[ -f $CONFIG_FILE ]]; then
        # Sourcing /etc/config_file first
        # because when updates to config file, this one is ALWAYS REPLACED.
        # This way, variables not updated inside the USER config folder are loaded anyway.
        if [[ -f "${ALT_CONF_DEST}/mcbash.conf" ]]; then
            load_formatted_config_file "${ALT_CONF_DEST}/mcbash.conf"
        fi
        load_formatted_config_file "$CONFIG_FILE"
    else
        if [[ -f "${ALT_CONF_DEST}/mcbash.conf" ]]; then
            load_formatted_config_file "${ALT_CONF_DEST}/mcbash.conf"
        else
            display_config_file_not_found
            load_hard_coded_config
        fi
    fi
}

load_formatted_config_file() {
    # Users may not know mcbash.conf is a simple
    # bash script. They might violate bash syntax
    # by putting spaces between variables id and
    # values. Here we try to anticipate and take
    # care of that.
    local config_filepath="$1"
    source <(sed 's/\ *=\ */=/g' $config_filepath)
}

load_hard_coded_config() {
    # those are default parameters to use in the
    # case no config file is found on the system
    # HARD_CODED_CONFIG_PLACEHOLDER
}
