#!/bin/sh

dns_name() {
	[[ -z ${dns+x} ]] && read -p "Server address : "${_BOLD}${_BLUE} dns
	[[ -n ${only_outputs_mac} ]] && tput sgr0 # can't place _RESET here due to last 'read' command. Help?
	#tput sgr0 # can't place _RESET here due to last 'read' command. Help?
	[[ $dns = "" ]] && unset dns && echo -ne "\r${_RED}You need to indicate a server address [ex: my-fakedns.org:8080]${_RESET}\n" && dns_name
	#[[ $(echo $dns | grep -o 'http://') = "" ]] && dns=$(echo 'http://'$dns)
	#dns=$(echo $dns | sed 's/\/$//') # if trailing "/" at the end of DNS, remove it
	#name=$(echo $dns | sed 's/http:\/\///' | sed 's/://;s/\///')
	name=$(echo $dns | sed "s/\/$// ; s/http:\/\/// ; s/:// ; s/\///")
	inspect_dns "${dns}"
}
