#!/bin/sh

URL_name() {
    if [[ -z "${URL+x}" ]]; then
        read -p "$SERVER_URL_PROMPT" URL
    fi
    if [[ -n $only_outputs_mac ]]; then
        #tput sgr0 # can't place _RESET here due to last 'read' command. Help?
        echo -n $'\e[0m'
    fi
    #tput sgr0 # can't place _RESET here due to last 'read' command. Help?
    if [[ "$URL" = "" ]]; then
        unset URL
        display_empty_URL
        URL_name
    fi

    SCANNED_URL=$(echo "$URL" | sed "s/\/$// ; s/http:\/\/// ; s/:// ; s/\///g")
    if ! inspect_URL "$URL" from_interactive; then
        unset URL
        URL_name
    fi
}

inspect_URL() {
    local url="$1"
    local mode=$2
    # Check if DNS is well formed URL or IP
    local URL_protocol="((https?|ftp)://)?"
    local URL_user_information="(.*:.*@)?"
    local URL_host="([-a-zA-Z0-9]+\.)?{1,2}[-a-zA-Z0-9]+\.[a-zA-Z0-9]{2,6}"
    local URL_IP="([0-9]{1,3}\.){3}[0-9]{1,3}"
    local URL_host_or_IP="($URL_host|$URL_IP)"
    local URL_port="(:[0-9]{1,5})?"
    local URL_path="(/([-_a-zA-Z0-9]+(/)?)?*)?"
    local URL_query_string="(\?.*)?"
    local URL_regexp="${URL_protocol}${URL_user_information}${URL_host_or_IP}${URL_port}${URL_path}${URL_query_string}"
    if ! [[ "$url" =~ $URL_regexp ]]; then
        display_bad_URL
        if [[ $mode == from_args ]]; then
            exit 1
        else
            return 1
        fi
    elif [[ "${url// /}" == "" ]]; then
        display_empty_URL $mode
        if [[ $mode == from_args ]]; then
            exit 1
        else
            return 1
        fi
    fi
}
