#!/bin/sh

# Check MAC randomly (between a range or not).
random_mac() {
	a=(1 2 3 4 5 6 7 8 9 0 A B C D E F)
	if [[ -n ${prefix} ]]; then
		mac_prefix=${prefix}
	else
		mac_prefix=${default_mac_prefix}
	fi
	number_chars_prefix=$(( $(echo ${mac_prefix} | sed 's/://g' | wc --chars) - 1 ))
	missing_mac_values=$(( max_mac_length - number_chars_prefix ))
	suffix=""
	for (( i=0;i<${missing_mac_values};i++ )); do
		suffix=$(echo $suffix)$(echo ${a[RANDOM%16]})
	done
	mac_without_colon=$(echo $mac_prefix | sed 's/://g')$(echo $suffix)
	new_mac=$(echo $mac_without_colon | sed -r 's/.{2}/&:/g ; s/:$//')

	# If --range is set, chose randomly between it
	if [[ -n ${range} ]]; then
		prev_mac=$(echo $mac)
		range_mac
		if [[ $(echo $new_mac) == $(echo $prev_mac) ]]; then
			random_mac
		fi
	fi

	# Encode mac
	mac=$(echo $new_mac)
	encoded_mac=$(echo $mac | sed 's/:/\%3A/g')
	#return
}

# Check MAC one by one from --range-from to --range-to.
seq_mac() {
	[[ -n ${last_mac_reached} ]] && \
		( [[ -n ${only_outputs_mac} ]] || echo "${_BOLD}${_CYAN}Range fullfiled${_RESET}" ) && \
		exit 0
	[[ -z ${first_mac+x} ]] && first_mac="$default_first_mac" && mac=$(echo $first_mac) && return # user first value of the MAC
	[[ $item == 1 ]] && mac=$(echo $first_mac) && return

	# if not '--no-checkpoint', save that MAC in checkpoint file
	[[ -z ${no_checkpoint+x} ]] && echo "${first_mac}" > "${destination}/checkpoint_${name}"

	new_mac=$(echo $first_mac)
	mac_simple=$(echo $new_mac |  tr '[:lower:]' '[:upper:]' | tr -d ':') && \
		mac_dec=$( printf '%d\n' 0x$mac_simple ) && \
		mac_add=$( expr $mac_dec + 1 ) && \
		mac_hex=$( printf '%012X\n' $mac_add ) && \
		new_mac=$(echo $mac_hex | sed 's/../&:/g;s/:$//') && \
		first_mac=$(echo $new_mac) && \
		mac=$(echo $new_mac) && \
		[[ -n ${last_mac} && $last_mac == $mac ]] && last_mac_reached=true
	#return
	encoded_mac=$(echo $mac | sed 's/:/\%3A/g')
}

# If --range is selected, MAC are created BETWEEN the range.
range_mac() {
	if [[ -z ${mac_low_dec+x} || -z ${mac_max_dec+x} ]]; then
		mac_low_basic=$(echo $range_from |  tr '[:lower:]' '[:upper:]' | tr -d ':')
		mac_low_dec=$( printf '%d\n' 0x$mac_low_basic )
		mac_max_basic=$(echo $range_to |  tr '[:lower:]' '[:upper:]' | tr -d ':')
		mac_max_dec=$( printf '%d\n' 0x$mac_max_basic )
	fi
	random_between_range=$(awk -v beginning=${mac_low_dec} -v finish=${mac_max_dec} 'BEGIN{srand();print int(rand()*(finish - beginning) + beginning) }')
	printf_string=$(echo "%0${max_mac_length}x\n")
	mac_hex=$(printf "${printf_string}" $random_between_range)
	new_mac=$(echo $mac_hex | tr '[:lower:]' '[:upper:]' | sed 's/../&:/g;s/:$//')
	encoded_mac=$(echo $mac | sed 's/:/\%3A/g')
}


read_mac_from_file() {
	if [[ -z ${started_reading_file+x} ]]; then
		started_reading_file=true
		line_to_read=0
		#max_number_of_lines_to_read=$(cat "$file_to_read_mac_from" | sed '/^$/d' | wc -l)
		max_number_of_lines_to_read=$(cat "$file_to_read_mac_from" | wc -l)
	fi
	if [[ $line_to_read -gt $max_number_of_lines_to_read ]]; then
		echo -e "\n${_YELLOW}End of MAC file.${_RESET}"
		exit 0
	fi
	line_to_read=$(( line_to_read + 1 ))
	mac=$(sed "${line_to_read}q;d" "$file_to_read_mac_from")
	if [[ $mac == "" ]]; then
		read_mac_from_file
	elif ! inspect_mac $mac "read_mac_from_file_function"; then
		read_mac_from_file
	fi
	encoded_mac=$(echo $mac | sed 's/:/\%3A/g')
}
