#!/bin/sh

declare -A GENRES
declare -A CHANNELS

get_genres() { 
    local get_genres_url="${URL}/portal.php?type=itv&action=get_genres&JsHttpRequest=1-xml"
    make_cookie
    random_user_agent
    random_x_user_agent
    curl -s "$get_genres_url" -H "User-Agent: ${user_agent}" -H "X-User-Agent: ${x_user_agent}" -H "Authorization: ${authorization}" -H "Cookie: ${cookie}"
}

store_genres() {
    # store GENRES in a hashtable to either:
    # - check if a language is available
    # - ensure channels are readable
    GENRES=() # reset global hashmap
    while read -r genre_id && read -r title; do
        GENRES["${title// /_}"]="$genre_id"
        #echo "$title"
    done < <(grep -oE "\"id\":\"([0-9]+|\*)\"|\"title\":\"[^\"]+\"" < <(get_genres) | sed -r "s/\"id\":\"([0-9]+)\"/\1/;s/\"title\":\"([^\"]+)\"/\1/")
}


get_channels() { 
    local get_channels_url="${URL}/portal.php?type=itv&action=get_ordered_list&genre=${genre_id}&force_ch_link_check=&fav=0&sortby=number&hd=0&p=0&JsHttpRequest=1-xml&from_ch_id=0"
    make_cookie
    random_user_agent
    random_x_user_agent
    curl -s "$get_channels_url" -H "User-Agent: ${user_agent}" -H "X-User-Agent: ${x_user_agent}" -H "Authorization: ${authorization}" -H "Cookie: ${cookie}"
}

store_channels() {
    CHANNELS=() # reset global hashmap
    local genre_id=
    if [[ $check_playable == true ]]; then
        for genre in "${!GENRES[@]}"; do
            if [[ $(grep -iE "$REGEX_GENRE" <<< "$genre") ]]; then
                genre_id="${GENRES[$genre]}"
                break
            fi
        done
    else
        genre_keys=("${!CHANNELS[@]}")
        genre_id="${GENRES[${genre_keys[RANDOM%${#genre_keys[@]}]}]}"
    fi

    local page=0
    get_channels_url="${URL}/portal.php?type=itv&action=get_ordered_list&genre=${genre_id}&force_ch_link_check=&fav=0&sortby=number&hd=0&p=${page}&JsHttpRequest=1-xml&from_ch_id=0"
    while read -r channel_id && read -r name; do
        CHANNELS["${name// /_}"]="$channel_id"
    done < <(grep -oE "\"id\":\"([0-9]+)\",\"name\":\"[^\"]+\"" < <(get_channels) | sed -r "s/\"id\":\"([0-9]+)\",\"name\":\"([^\"]+)\"/\1\n\2/")
}

user_wanted_genre_matches() {
    local match=false
    for genre in "${!GENRES[@]}"; do
        if [[ $(grep -iE "$REGEX_GENRE" <<< "$genre") ]]; then
            match=true
            break
        fi
    done

    if [[ $match == false ]]; then false; fi
}

user_can_play_channel() {
    local genre_keys=("${!CHANNELS[@]}")
    local channel_id="${CHANNELS[${genre_keys[RANDOM%${#genre_keys[@]}]}]}"

    # https://stackoverflow.com/a/64827805
    local ffprobe_timeout=5 # seconds
    #timeout ${ffprobe_timeout}s ffprobe -timeout 3000000 -loglevel quiet "${URL}/play/live.php?mac=${mac}&stream=${channel_id}&extension=ts"
    ffprobe -timeout ${ffprobe_timeout}000000 -loglevel quiet "http://${URL}/play/live.php?mac=${mac}&stream=${channel_id}&extension=ts"
}
